import React, { useState, useMemo, useEffect } from 'react';
import {
  calculateAttendance,
  calculateAggregateAttendance,
  SubjectAttendance,
} from '../lib/student/attendance';
import { AttendanceSummary } from '../components/student/AttendanceSummary';
import {
  Plus,
  Trash2,
  Copy,
  Check,
  RotateCcw,
  BookOpen,
  Calendar,
  Layers,
  HelpCircle,
  AlertCircle
} from 'lucide-react';
import { formatNumber } from '../lib/formatters';

const STORAGE_KEY = 'toolnest_subject_attendance_list';

const INITIAL_SUBJECTS: SubjectAttendance[] = [
  { id: '1', name: 'Data Structures & Algorithms', total: 42, attended: 35, requiredPercentage: 75 },
  { id: '2', name: 'Computer Networks', total: 38, attended: 26, requiredPercentage: 75 },
  { id: '3', name: 'Software Engineering', total: 30, attended: 25, requiredPercentage: 75 },
  { id: '4', name: 'Discrete Mathematics', total: 36, attended: 29, requiredPercentage: 75 },
];

export const AttendanceCalculator: React.FC = () => {
  // Mode: 'single' for quick calculation, 'tracker' for multi-subject course tracker
  const [activeTab, setActiveTab] = useState<'single' | 'tracker'>('single');

  // Single mode state
  const [totalClasses, setTotalClasses] = useState<string>('40');
  const [attendedClasses, setAttendedClasses] = useState<string>('28');
  const [requiredPercentage, setRequiredPercentage] = useState<number>(75);

  // Multi-subject tracker state
  const [subjects, setSubjects] = useState<SubjectAttendance[]>(() => {
    try {
      const stored = localStorage.getItem(STORAGE_KEY);
      if (stored) {
        return JSON.parse(stored);
      }
    } catch {}
    return INITIAL_SUBJECTS;
  });

  const [copied, setCopied] = useState<boolean>(false);

  // Save subjects to local storage
  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(subjects));
    } catch {}
  }, [subjects]);

  // Validation for single mode
  const totalNum = parseInt(totalClasses, 10);
  const attendedNum = parseInt(attendedClasses, 10);

  const validationError = useMemo(() => {
    if (isNaN(totalNum) || totalNum < 0) {
      return 'Total classes conducted must be a non-negative integer.';
    }
    if (isNaN(attendedNum) || attendedNum < 0) {
      return 'Attended classes must be a non-negative integer.';
    }
    if (attendedNum > totalNum) {
      return 'Attended classes cannot exceed total classes conducted.';
    }
    return null;
  }, [totalNum, attendedNum]);

  // Single calculation result
  const singleResult = useMemo(() => {
    if (validationError || isNaN(totalNum) || isNaN(attendedNum)) {
      return null;
    }
    return calculateAttendance(totalNum, attendedNum, requiredPercentage);
  }, [totalNum, attendedNum, requiredPercentage, validationError]);

  // Multi-subject aggregate calculation
  const aggregateResult = useMemo(() => {
    return calculateAggregateAttendance(subjects);
  }, [subjects]);

  // Multi-subject handlers
  const handleAddSubject = () => {
    const newSubject: SubjectAttendance = {
      id: Date.now().toString(),
      name: `Course #${subjects.length + 1}`,
      total: 30,
      attended: 24,
      requiredPercentage: 75,
    };
    setSubjects([...subjects, newSubject]);
  };

  const handleUpdateSubject = (id: string, field: keyof SubjectAttendance, value: string | number) => {
    setSubjects((prev) =>
      prev.map((s) => (s.id === id ? { ...s, [field]: value } : s))
    );
  };

  const handleIncrementAttended = (id: string) => {
    setSubjects((prev) =>
      prev.map((s) => {
        if (s.id === id) {
          return {
            ...s,
            total: s.total + 1,
            attended: s.attended + 1,
          };
        }
        return s;
      })
    );
  };

  const handleIncrementMissed = (id: string) => {
    setSubjects((prev) =>
      prev.map((s) => {
        if (s.id === id) {
          return {
            ...s,
            total: s.total + 1,
          };
        }
        return s;
      })
    );
  };

  const handleRemoveSubject = (id: string) => {
    setSubjects((prev) => prev.filter((s) => s.id !== id));
  };

  const handleResetSingle = () => {
    setTotalClasses('40');
    setAttendedClasses('28');
    setRequiredPercentage(75);
  };

  const handleCopySummary = () => {
    if (activeTab === 'single' && singleResult) {
      const text = `Attendance Report:
• Classes Attended: ${singleResult.attended} / ${singleResult.total}
• Current Attendance: ${formatNumber(singleResult.currentPercentage, 1)}%
• Required Criteria: ${singleResult.requiredPercentage}%
• Status: ${singleResult.message}
Generated by ToolNest Attendance Calculator`;
      navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } else if (activeTab === 'tracker') {
      let lines = `Semester Attendance Report:\n• Total Classes: ${aggregateResult.totalClasses} | Attended: ${aggregateResult.attendedClasses} (${formatNumber(aggregateResult.overallPercentage, 1)}%)\n\nSubject Breakdown:\n`;
      subjects.forEach((s) => {
        const pct = s.total > 0 ? (s.attended / s.total) * 100 : 0;
        lines += `• ${s.name}: ${s.attended}/${s.total} (${formatNumber(pct, 1)}% - req ${s.requiredPercentage}%)\n`;
      });
      lines += '\nGenerated by ToolNest Attendance Calculator';
      navigator.clipboard.writeText(lines);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className="space-y-8 max-w-4xl mx-auto">
      {/* Navigation Mode Pill Tabs */}
      <div className="flex items-center justify-between flex-wrap gap-4 border-b border-neutral-200 dark:border-neutral-800 pb-4">
        <div className="flex items-center p-1.5 rounded-2xl bg-neutral-100 dark:bg-neutral-850 border border-neutral-200 dark:border-neutral-750">
          <button
            type="button"
            onClick={() => setActiveTab('single')}
            className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-bold transition-all ${
              activeTab === 'single'
                ? 'bg-white dark:bg-neutral-900 text-neutral-900 dark:text-neutral-100 shadow-sm'
                : 'text-neutral-600 dark:text-neutral-400 hover:text-neutral-900 dark:hover:text-neutral-100'
            }`}
          >
            <BookOpen className="w-4 h-4" />
            <span>Single Subject / Quick Calculator</span>
          </button>
          <button
            type="button"
            onClick={() => setActiveTab('tracker')}
            className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-bold transition-all ${
              activeTab === 'tracker'
                ? 'bg-white dark:bg-neutral-900 text-neutral-900 dark:text-neutral-100 shadow-sm'
                : 'text-neutral-600 dark:text-neutral-400 hover:text-neutral-900 dark:hover:text-neutral-100'
            }`}
          >
            <Layers className="w-4 h-4" />
            <span>Multi-Course Semester Tracker</span>
          </button>
        </div>

        {/* Global actions */}
        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={handleCopySummary}
            className="flex items-center gap-1.5 px-3 py-2 rounded-xl border border-neutral-200 dark:border-neutral-700 bg-white dark:bg-neutral-900 text-xs font-semibold text-neutral-700 dark:text-neutral-300 hover:bg-neutral-50 dark:hover:bg-neutral-800 shadow-sm transition-colors"
          >
            {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
            <span>{copied ? 'Copied' : 'Copy Report'}</span>
          </button>
        </div>
      </div>

      {activeTab === 'single' ? (
        /* SINGLE SUBJECT QUICK CALCULATOR */
        <div className="space-y-8">
          {/* Inputs Section */}
          <div className="p-6 rounded-2xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 shadow-sm space-y-6">
            <h3 className="text-base font-bold text-neutral-900 dark:text-white flex items-center gap-2">
              <Calendar className="w-5 h-5 text-emerald-600" />
              <span>Class Attendance Information</span>
            </h3>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-5">
              {/* Total Classes Held */}
              <div>
                <label htmlFor="total-classes-input" className="block text-xs font-semibold text-neutral-700 dark:text-neutral-300 mb-1.5">
                  Total Classes Conducted
                </label>
                <input
                  id="total-classes-input"
                  type="number"
                  min="0"
                  value={totalClasses}
                  onChange={(e) => setTotalClasses(e.target.value)}
                  placeholder="e.g. 40"
                  className="w-full px-4 py-2.5 rounded-xl border border-neutral-200 dark:border-neutral-700 bg-neutral-50 dark:bg-neutral-950 font-mono text-base font-bold text-neutral-900 dark:text-neutral-100 focus:outline-none focus:ring-2 focus:ring-emerald-500/30"
                />
                <span className="block text-[11px] text-neutral-400 mt-1">
                  Total lecture periods or labs held so far.
                </span>
              </div>

              {/* Classes Attended */}
              <div>
                <label htmlFor="attended-classes-input" className="block text-xs font-semibold text-neutral-700 dark:text-neutral-300 mb-1.5">
                  Classes Attended (Present)
                </label>
                <input
                  id="attended-classes-input"
                  type="number"
                  min="0"
                  value={attendedClasses}
                  onChange={(e) => setAttendedClasses(e.target.value)}
                  placeholder="e.g. 28"
                  className="w-full px-4 py-2.5 rounded-xl border border-neutral-200 dark:border-neutral-700 bg-neutral-50 dark:bg-neutral-950 font-mono text-base font-bold text-neutral-900 dark:text-neutral-100 focus:outline-none focus:ring-2 focus:ring-emerald-500/30"
                />
                <span className="block text-[11px] text-neutral-400 mt-1">
                  Number of lectures you were physically present for.
                </span>
              </div>
            </div>

            {/* Required Criteria Threshold Presets & Slider */}
            <div>
              <div className="flex items-center justify-between mb-2">
                <label className="text-xs font-semibold text-neutral-700 dark:text-neutral-300">
                  Required Minimum Attendance Threshold
                </label>
                <span className="font-mono text-sm font-bold text-emerald-600 dark:text-emerald-400">
                  {requiredPercentage}%
                </span>
              </div>

              {/* Presets */}
              <div className="flex items-center gap-2 flex-wrap mb-3">
                {[65, 70, 75, 80, 85, 90].map((pct) => (
                  <button
                    key={pct}
                    type="button"
                    onClick={() => setRequiredPercentage(pct)}
                    className={`px-3 py-1.5 rounded-xl text-xs font-semibold border transition-all ${
                      requiredPercentage === pct
                        ? 'bg-neutral-900 text-white dark:bg-white dark:text-neutral-900 border-transparent shadow-sm'
                        : 'border-neutral-200 dark:border-neutral-800 bg-neutral-50 dark:bg-neutral-950 text-neutral-600 dark:text-neutral-400 hover:border-neutral-300'
                    }`}
                  >
                    {pct}%
                  </button>
                ))}
              </div>

              <input
                type="range"
                min="40"
                max="100"
                step="1"
                value={requiredPercentage}
                onChange={(e) => setRequiredPercentage(parseInt(e.target.value, 10))}
                className="w-full accent-emerald-600 cursor-pointer"
              />
            </div>

            {validationError && (
              <div className="flex items-center gap-2 p-3 rounded-xl bg-rose-50 dark:bg-rose-950/40 border border-rose-200 dark:border-rose-900 text-xs text-rose-700 dark:text-rose-400">
                <AlertCircle className="w-4 h-4 shrink-0" />
                <span>{validationError}</span>
              </div>
            )}
          </div>

          {/* Results Summary Card */}
          {singleResult && (
            <AttendanceSummary result={singleResult} />
          )}
        </div>
      ) : (
        /* MULTI-COURSE SEMESTER TRACKER */
        <div className="space-y-6">
          {/* Aggregate Semester Banner */}
          <div className="p-6 rounded-2xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 shadow-sm">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div>
                <span className="text-xs font-bold uppercase tracking-wider text-neutral-400">
                  Semester Aggregate Overview
                </span>
                <div className="flex items-baseline gap-2 mt-1">
                  <span className="font-mono text-3xl font-black text-neutral-900 dark:text-white">
                    {formatNumber(aggregateResult.overallPercentage, 1)}%
                  </span>
                  <span className="text-xs text-neutral-500">
                    ({aggregateResult.attendedClasses} attended / {aggregateResult.totalClasses} total)
                  </span>
                </div>
              </div>

              <div className="flex items-center gap-3">
                <div className="text-right">
                  <div className="text-xs font-semibold text-neutral-500">Criteria Shortage</div>
                  <div className="font-bold text-sm text-neutral-800 dark:text-neutral-200">
                    {aggregateResult.belowThresholdCount === 0 ? (
                      <span className="text-emerald-600">All Courses Safe</span>
                    ) : (
                      <span className="text-rose-600">
                        {aggregateResult.belowThresholdCount} {aggregateResult.belowThresholdCount === 1 ? 'Subject' : 'Subjects'} Below Target
                      </span>
                    )}
                  </div>
                </div>

                <button
                  type="button"
                  onClick={handleAddSubject}
                  className="flex items-center gap-1.5 px-4 py-2.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs shadow-sm transition-colors"
                >
                  <Plus className="w-4 h-4" />
                  <span>Add Course</span>
                </button>
              </div>
            </div>
          </div>

          {/* Course List Rows */}
          <div className="space-y-3">
            {subjects.map((sub, index) => {
              const res = calculateAttendance(sub.total, sub.attended, sub.requiredPercentage);
              const isSafe = res.status === 'above' || res.status === 'exact';

              return (
                <div
                  key={sub.id}
                  className="p-4 rounded-2xl border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900 shadow-sm space-y-3"
                >
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                    <div className="flex items-center gap-2">
                      <span className="font-mono text-xs text-neutral-400">
                        {(index + 1).toString().padStart(2, '0')}.
                      </span>
                      <input
                        type="text"
                        value={sub.name}
                        onChange={(e) => handleUpdateSubject(sub.id, 'name', e.target.value)}
                        className="text-sm font-bold text-neutral-900 dark:text-neutral-100 bg-transparent border-b border-dashed border-neutral-300 dark:border-neutral-700 focus:outline-none focus:border-emerald-500"
                      />
                    </div>

                    <div className="flex items-center gap-3">
                      <div className="flex items-center gap-1">
                        <span className="text-xs text-neutral-400">Req:</span>
                        <input
                          type="number"
                          min="40"
                          max="100"
                          value={sub.requiredPercentage}
                          onChange={(e) => handleUpdateSubject(sub.id, 'requiredPercentage', parseInt(e.target.value) || 75)}
                          className="w-12 px-1.5 py-0.5 rounded border border-neutral-200 dark:border-neutral-700 text-xs font-mono text-center font-bold bg-neutral-50 dark:bg-neutral-950"
                        />
                        <span className="text-xs text-neutral-400">%</span>
                      </div>

                      <span
                        className={`font-mono text-sm font-black px-2.5 py-1 rounded-lg ${
                          isSafe
                            ? 'bg-emerald-50 dark:bg-emerald-950/40 text-emerald-700 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-900'
                            : 'bg-rose-50 dark:bg-rose-950/40 text-rose-700 dark:text-rose-400 border border-rose-200 dark:border-rose-900'
                        }`}
                      >
                        {formatNumber(res.currentPercentage, 1)}%
                      </span>

                      <button
                        type="button"
                        onClick={() => handleRemoveSubject(sub.id)}
                        disabled={subjects.length <= 1}
                        className="p-1.5 rounded-lg text-neutral-400 hover:text-rose-500 disabled:opacity-20 transition-colors"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </div>

                  {/* Attendance Controls & Quick Add buttons */}
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pt-2 border-t border-neutral-100 dark:border-neutral-800/80">
                    <div className="flex items-center gap-4 text-xs">
                      <div>
                        <span className="text-neutral-500">Attended: </span>
                        <input
                          type="number"
                          min="0"
                          value={sub.attended}
                          onChange={(e) => handleUpdateSubject(sub.id, 'attended', parseInt(e.target.value) || 0)}
                          className="w-14 px-1.5 py-1 rounded border border-neutral-200 dark:border-neutral-700 text-xs font-mono font-bold bg-neutral-50 dark:bg-neutral-950"
                        />
                      </div>
                      <div>
                        <span className="text-neutral-500">Total: </span>
                        <input
                          type="number"
                          min="0"
                          value={sub.total}
                          onChange={(e) => handleUpdateSubject(sub.id, 'total', parseInt(e.target.value) || 0)}
                          className="w-14 px-1.5 py-1 rounded border border-neutral-200 dark:border-neutral-700 text-xs font-mono font-bold bg-neutral-50 dark:bg-neutral-950"
                        />
                      </div>
                    </div>

                    <div className="flex items-center gap-2">
                      <span className="text-xs text-neutral-500 dark:text-neutral-400 mr-1">
                        {res.status === 'above'
                          ? `Can skip ${res.classesCanMiss} lectures`
                          : res.classesToAttend > 0
                          ? `Attend next ${res.classesToAttend} lectures`
                          : 'On track'}
                      </span>

                      {/* Quick Log Buttons */}
                      <button
                        type="button"
                        onClick={() => handleIncrementAttended(sub.id)}
                        className="px-2.5 py-1 rounded-lg bg-emerald-50 dark:bg-emerald-950/40 text-emerald-700 dark:text-emerald-400 border border-emerald-200 dark:border-emerald-800 text-[11px] font-bold hover:bg-emerald-100 dark:hover:bg-emerald-900 transition-colors"
                        title="Mark present for 1 class"
                      >
                        +1 Present
                      </button>
                      <button
                        type="button"
                        onClick={() => handleIncrementMissed(sub.id)}
                        className="px-2.5 py-1 rounded-lg bg-rose-50 dark:bg-rose-950/40 text-rose-700 dark:text-rose-400 border border-rose-200 dark:border-rose-800 text-[11px] font-bold hover:bg-rose-100 dark:hover:bg-rose-900 transition-colors"
                        title="Mark absent for 1 class"
                      >
                        +1 Absent
                      </button>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
};
